//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class myTask
    {
        public int taskid { get; set; }
        public string taskname { get; set; }
        public string taskdetails { get; set; }
        public string referdby { get; set; }
        public Nullable<System.DateTime> requestDate { get; set; }
        public string taskStatus { get; set; }
    }
}
